config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/index',to: 'dogs#index'
  
  
  get '/', to: 'pages#home', as: 'home'
  get '/team', to: 'pages#team', as: 'team'
  get '/about', to: 'pages#about', as: 'about'

  get  '/signup',  to: 'dogs#new', as: 'signup'
  post '/signup',  to: 'dogs#create'

  get    '/login',   to: 'sessions#new', as: 'login'
  post   '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
    has_secure_password validations: false

    validates :name, presence: true
    validates :image, presence: true
    validates  :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
    before_action :logged_in_dog, only: [:index]

    def index
    end
    
    def new
        @dog = Dog.new
    end
    
    def create
        @dog = Dog.new(dogs_params)
        if @dog.save
          flash[:success] = "Dog successfully created"
          redirect_to home_path
        else
          flash[:error] = "Something went wrong"
          render 'new'
        end
    end
    

#Autorizacion, pregunta si el usuario esta logueado
def logged_in_dog
    unless logged_in?
      redirect_to '/'
    end
  end

    private
    def dogs_params
        params.require(:dog).permit(:name,:password,:image)
    end

    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :logged_in_dog, only: [:team, :about]
    def home
    end

    def team
    end

    def about
    end

    #Autorizacion, pregunta si el usuario esta logueado
    def logged_in_dog
        unless logged_in?
          redirect_to '/'
        end
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end

    def create
        dog = Dog.find_by(name: params[:session][:name])
        if dog && dog.authenticate(params[:session][:password])
          log_in dog #metodo que esta en el helper se le envia el dog
          redirect_to '/index'
        else
          render 'new'
        end
    end

    def destroy
      log_out
      redirect_to home_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def log_in(dog) #recibe el dog enviado desde el controlador
        #Este metodo modifica la cookie implantada por rails
        session[:dog_id] = dog.id
    end

    def current_dog
        if session[:dog_id]
            @current_dog = @current_dog || Dog.find_by(id:session[:dog_id])
        end
    end

    def logged_in? #devuelve true o false
        !current_dog.nil?
    end
    
    #modifica la cookie quitando el campo dog_id
    def log_out
        session.delete(:dog_id)
        @current_dog = nil
    end
end

app/views/dogs/_nav_dog.html.erb
  <!--Navbar Dog-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   <%= link_to 'Authentication Dog', '/index',class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNav">
    <ul class="navbar-nav">

          <li class="nav-item">
        <%= link_to 'Team', team_path, class:"nav-link" %>
      </li>
          <li class="nav-item">
        <%= link_to 'About', about_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to 'Log out', logout_path,method: :delete, class:"nav-link" %>
        
      </li>
      </ul>
  </div>
</nav>

app/views/dogs/_nav_home.html.erb
  <!--Navbar home-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Authentication Dog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/login">Sign in<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/signup">Sign up</a>
      </li>
      </ul>
  </div>
</nav>

app/views/dogs/index.html.erb
<% if logged_in?%>
<%= render 'dogs/nav_dog'%>
<% else %>
<%= render 'pages/nav_home'%>
<% end %>

<style>
body , .card {
  height: 100%;
  background-color: #333;
}

.container .card{
  display: -ms-flexbox;
  display: flex-column;
  color: #fff;
  text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5);
  box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);
}
</style>

<div class="container">
    <div class="card">
        <div class="card-header">

            <h1>Hola <%= current_dog.name %></h1>

        </div>
    <div class="card-body">

        <img src="<%= current_dog.image %>" alt="image" width="600px">

    </div>

</div>

app/views/dogs/new.html.erb
<%= render 'pages/nav_home'%>


<div class="container mt-4">

<div class="row">
<div class="col-md-6">
  <% if @dog.errors%>
<div class="alert alert-warning" role="alert">
  <% @dog.errors.full_messages.each do |error|%>
    <h6> <%= error %> </h6>
  <% end %>
</div>
<% end %>
</div></div>
  <div class="row">
    <div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <h1 class="text-center">Sign up to Dog-App</h1>
        </div>
        <div class="card-body"> 
            <%= form_for(@dog, url: signup_path)  do |f| %>
        <div class="input-group mt-3 mb-3">
        <span class="input-group-prepend input-group-text"><i class="fas fa-dog"></i></span>
          <%= f.text_field :name, class: "form-control input-lg", placeholder: "Dog Name" %>
        </div>

        <div class="input-group mt-3 mb-3">
        <span class="input-group-prepend input-group-text"><i class="fas fa-paw"></i></span>
          <%= f.text_field :image, class: "form-control input-lg", placeholder: "Url-image" %>
        </div>

        <div class="input-group mt-3 mb-3">
        <span class="input-group-prepend input-group-text"><i class="fas fa-key"></i></span>
          <%= f.password_field :password, class: "form-control input-lg", placeholder: "Password" %>
        </div>
        </div>
        <div class="card-footer">
        <div class="actions">
          <%= f.submit class: "btn btn-primary btn-block btn-lg" %>
        </div>
      <% end %>
        </div> 
        </div>
             
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthDog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/pages/_nav_home.html.erb
  <!--Navbar home-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Authentication Dog', home_path,class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
      <%= link_to 'Sign in', login_path, class:"nav-link" %><span class="sr-only">(current)</span>
      </li>
      <li class="nav-item">
      <%= link_to 'Sign up', signup_path, class:"nav-link" %>
      </li>
      </ul>
  </div>
</nav>

app/views/pages/about.html.erb
<%= render 'dogs/nav_dog'%>

<style>
body {
  height: 100%;
  background-color: #333;
}

.container {
  display: -ms-flexbox;
  display: flex-column;
  color: #fff;
  text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5);
  box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);
}
</style>

<div class="container">
<h1>Este es el about de <%= current_dog.name%>
</h1></div>

app/views/pages/home.html.erb
<%= render 'pages/nav_home'%>
<style>
/*
 * Globals
 */

/* Links */
a,
a:focus,
a:hover {
  color: #fff;
}

/* Custom default button */
.btn-secondary,
.btn-secondary:hover,
.btn-secondary:focus {
  color: #333;
  text-shadow: none; /* Prevent inheritance from `body` */
  background-color: #fff;
  border: .05rem solid #fff;
}


/*
 * Base structure
 */

body {
  height: 100%;
  background-color: #333;
}

.container {
  display: -ms-flexbox;
  display: flex-column;
  color: #fff;
  text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5);
  box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);
}

/*
.cover-container {
  max-width: 42em;
}
*/

/*
 * Header
 */
.masthead {
  margin-bottom: 2rem;
}

.masthead-brand {
  margin-bottom: 0;
}

.nav-masthead .nav-link {
  padding: .25rem 0;
  font-weight: 700;
  color: rgba(255, 255, 255, .5);
  background-color: transparent;
  border-bottom: .25rem solid transparent;
}

.nav-masthead .nav-link:hover,
.nav-masthead .nav-link:focus {
  border-bottom-color: rgba(255, 255, 255, .25);
}

.nav-masthead .nav-link + .nav-link {
  margin-left: 1rem;
}

.nav-masthead .active {
  color: #fff;
  border-bottom-color: #fff;
}

@media (min-width: 48em) {
  .masthead-brand {
    float: left;
  }
  .nav-masthead {
    float: right;
  }
}


/*
 * Cover
 */
.cover {
  padding: 0 1.5rem;
}
.cover .btn-lg {
  padding: .75rem 1.25rem;
  font-weight: 700;
}


/*
 * Footer
 */
.mastfoot {
  color: rgba(255, 255, 255, .5);
}
</style>

<div class="container text-center m-4">



      <main role="main" class="inner cover">
        <h1 class="cover-heading">Welcome to the Auth-Dog Application</h1>
        <p class="lead">Register your dog, so you start enjoying the benefits of our store !. Gifts, products for care, health and countless things that will make you happier.</p>
        <p class="lead">
          <a href="/signup" class="btn btn-lg btn-secondary">Sign Up</a>
          <a href="/login" class="btn btn-lg btn-secondary">Sign In</a>

        </p>
      </main>

      <img src="https://www.elespectador.com/sites/default/files/cromos/image_main/cachorros-aliemento-condiciones.jpg" alt="">

      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>Designed by Carlos Romero and Yony Briñez <a href="https://twitter.com/mdo">Github</a>.</p>
        </div>
      </footer>
</div>

app/views/pages/team.html.erb
<%= render 'dogs/nav_dog'%>

<style>
body {
  height: 100%;
  background-color: #333;
}

.container {
  display: -ms-flexbox;
  display: flex-column;
  color: #fff;
  text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5);
  box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);
}
</style>

<div class="container">
<h1>Este es el team de <%= current_dog.name%>
</h1></div>